spring:
  rabbitmq:
    host: 192.168.9.131
    username: yueqian
    password: yueqian
  profiles:
    active: redis

custom:
  rabbitmq:
    solr:
      host: http://localhost:8083/
      insert: /solr/insert

dubbo:
  application:
    name: portal-dubbo
  registry:
    address: zookeeper://192.168.9.128:2181