dubbo:
  application:
    name: order-dubbo
  registry:
    address: zookeeper://192.168.9.128:2181

#视图解析器
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: commons,redis,rabbitmq
server:
  port: 8086
