dubbo:
  application:
    name: search-dubbo
  registry:
    address: zookeeper://192.168.9.128:2181

#视图解析器
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: commons,redis,rabbitmq
  data:
    solr:
      host: http://192.168.9.132:8080/solr
server:
  port: 8083


custom:
  solr:
    defaultCollection: collection1
  search:
    num: 12